version: '2'

services:
  webserver:
    ports:
      - "8086:80"
      - "4436:443"
  db:
    ports:
      - "33066:3306"
    expose:
      - "3306"
  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - "5672"
      - "15672"